- src/mtk.cpp
On QURT there is a warning coming up that the buffer size is
too small.  This change should silence it.
> mtk: raise buffer size for Snapdragon

- src/ubx.cpp
_buf contains a payload_rx_nav_pvt, but we accessed it as
payload_rx_nav_timeutc (copy-paste mistake).
> ubx: fix time_utc_usec, if NAV-PVT message received

- src/ubx.cpp
- src/ubx.h
Added new ```void setSurveyInSpecs(uint32_t survey_in_acc_limit, uint32_t survey_in_min_dur)``` which allows QGC to have configurable survey in specs.
> Configurable survey in support

- src/ashtech.cpp
- src/ashtech.h
- src/gps_helper.h
- src/mtk.cpp
- src/rtcm.cpp
- src/rtcm.h
- src/ubx.cpp
- src/ubx.h
This adds heading and RTK support for the Trimble MB-Two using the Ashtech driver (including base station survey-in).
The MB-Two is expected to have 2 antennas attached, which is then used to compute a heading angle.
I had some problems with auto-detection when the baudrate changed - the device became unresponsive for 10's of seconds. This is why the baudrate can now be set to a fixed value. However my latest tests showed that this is much better now, I'm not sure why. I'll do further testing, but this can still be merged as is.
Further changes are explained in the individual commits.
I have not tested it on another Ashtech GPS device, since I don't have any.
> Add Trimble MB-Two GPS support

- src/ubx.cpp
- src/ubx.h
@bkueng @sirPerna This should fix the issues with pre-configured GPS modules which do not accept serial config commands. I don't have one of these modules so I need to test this first. Matching Firmware PR:
https://github.com/PX4/Firmware/pull/6171
> Untested: UBX driver: Reset module as part of config

- src/ashtech.cpp
- src/ashtech.h
- src/base_station.h
- src/gps_helper.cpp
- src/gps_helper.h
- src/ubx.cpp
- src/ubx.h
- Avoids the need for survey-in if the position is already known
- The base station position can be read from SurveyInStatus
- Support for both u-Blox & Trimble with a common interface
- Split off a new base class GPSBaseStationSupport that contains the
base station settings
Tested on both Trimble MB-Two & u-blox M8P.
> Base station: add ability to directly set the position

- src/ashtech.cpp
- src/gps_helper.h
- src/mtk.cpp
- src/ubx.cpp
- src/ubx.h
Protocol version 27 (used with F9* devices) deprecates several messages:
- CFG-RRT
- CFG-MSG
- CFG-RATE
- CFG-CFG
- CFG-NAV5
- CFG-TMODE3
- MON-HW
With the new messages:
- CFG-VAL{GET,SET,DEL}
- MON-RF
So this affects a large part of the driver, including auto-config.
The auto-detection now first tries to use the new config command,
and based on the result of that we know if we can use protocol version 27
or higher.
- add board detection
- 10Hz update rate for F9*
- higher baudrate for M8* and F9* devices (115200 instead of 38400). Reduces latency.
- reduce read buffer size by 100 bytes
- remove unnecessary initialization of heading 
-  enable Galileo, BeiDou and GLONASS code-phase biases RTCM output (RTK base)
- remove unused SBAS option 
- remove config reset on startup, because:
- It …
> u-blox: protocol update to version 27 and more

- src/ashtech.cpp
- src/sbf.cpp
- src/ubx.cpp
- src/ubx.h
- 2 fixes for the u-blox F9P:
- switch from NAV-SVINFO to NAV-SAT (required for protocol 27+)
- allow multiple MON-RF blocks
- Fixes for septentrio:
- off-by-one error
- configuration simplification
Tested against the Sparkfun F9P (https://www.sparkfun.com/products/15136) and the Septentrio AsteRx-m2 UAS (that one only bench-tested).
> Septentrio & u-blox F9P updates

- src/sbf.cpp
We have encountered a case on an AsteRx-m2 UAS where do-not-use values were being reported in velocity fields without a corresponding error code or fix-type 0. Support confirmed that this is happening. This adds a check for known invalid data and sets the appropriate flags.
Unfortunately I have currently no hardware to test this anymore. Not 100% sure if this is the best way to do the checks.
Note that if the glitches are short, EKF will reject the extreme velocity values and it goes unnoticed. Other estimators might behave differently.
do-not-use value in this case was `-2 * 10^10`
> [CRITICAL] SBF fix for do-not-use values

- src/ubx.cpp
Bug:
In Auto baud rate, if the gps current baud rate is not the first tested,
desired baud rate will be set to the pre 2.7 default bauderate
(UBX_TX_CFG_PRT_BAUDRATE)
For 2.7 and high it should be set to UBX_CFG_KEY_CFG_UART1_BAUDRATE
Solution:
Wait to be sure that protocol version is lower than 2.7 before setting
desired_baudrate to UBX_TX_CFG_PRT_BAUDRATE
> ubx: fix baud rate search

- src/ashtech.cpp
- src/ashtech.h
- src/emlid_reach.cpp
- src/emlid_reach.h
- src/mtk.cpp
- src/mtk.h
- src/sbf.cpp
- src/sbf.h
- src/ubx.cpp
- src/ubx.h
For https://github.com/PX4/Firmware/pull/14447
And https://github.com/mavlink/qgroundcontrol/pull/8587
> updated to sensor_gps_s

- src/gps_helper.h
This throws a warning, in QGC warnings are errors so QGC master currently does not compile.
> fixed unused arg compiler warning

- src/ubx.cpp
- src/ubx.h
Apparently a 10Hz update rate restricts the number of used satellites to 16, and as soon as the update rate is reduced, the number of used satellites increases.
The datasheet only mentions that the navigation rate can go up to 25Hz.
Cross-tested on an F9P.
> u-blox: reduce update rate for M9N to 5Hz (instead of 10Hz)

- src/ashtech.cpp
- src/ashtech.h
- src/femtomes.cpp
- src/gps_helper.cpp
- src/sbf.cpp
- src/ubx.cpp
- src/ubx.h
Hello,
This PR accomplishes a bit of cleanup and functionality in the following:
- The Satellite PRN code field has been added in the Ashtek and uBlox drivers and the field order in the drivers now matches the message field list order,
- C-style casts have been replaced with static_casts<>(),
- Whitespace formatting has been standardized to be self-consistent within the header files,
- Variable lists have been alphabetized/organized to be more easily readable to the extent allowed by initialization orders,
This PR has been bench tested on a Holybro pixhawk 4 and pixhawk 4 gps module.
Please let me know if you have any questions on this PR.  Thanks!
-Mark
> Add PRN (SBAS code) to the U-Blox and Ashtech GPS drivers, standardize tab/space formatting within the files, alphabetize ordering

- src/ubx.cpp
- src/ubx.h
To maintain backwards compatibility with the GPS_STATUS MAVLink message, the `svId` was also added to `satellite_info.prn`.
Because `satellite_info.svid` is only 8 bit wide, the new `gnssId:svId` format used in the NAV-SAT message does not fit into the uORB topic. Therefore the data from NAV-SAT is converted to the old format from NAV-SVINFO.
> ubx: fix #63: NAV-SAT/ SVINFO parser bug

- src/ubx.cpp
The uart2 is used to connect two GPS to enable GPS heading measurements.
Lowering this baudrate has shown higher SNR.
> ubx: change uart2_baudrate to 230400

- src/ubx.cpp
The wrong variable was used in the NAV-SAT parser, where the new satellite ID is converted to the old (NAV-SVINFO) scheme.
> ubx: fix NAV-SAT svId conversion (SVINFO compatibility)

- src/ashtech.cpp
- src/ashtech.h
- src/emlid_reach.cpp
- src/emlid_reach.h
- src/femtomes.cpp
- src/femtomes.h
- src/gps_helper.h
- src/mtk.cpp
- src/mtk.h
- src/sbf.cpp
- src/sbf.h
- src/ubx.cpp
- src/ubx.h
A new PX4 parameter is needed to configure the set of used GNSS systems. This PR changes the `GPSHelper::configure()` interface method used by the GPS drivers to include another parameter for the configuration (with the same data format, as the PX4 parameter).
Additionally the actual feature of setting the GNSS configuration was implemented for uBlox devices.
See https://github.com/PX4/PX4-GPSDrivers/issues/68 for details.
> Implement new parameter for GNSS system selection

- src/ubx.cpp
- src/ubx.h
title self explanatory, this should provide more insightful information about GPS jamming state.
From u-blox Integration Manual
> The field flags of the UBX-MON-RF message can be used as an indicator for both broadband andcontinuous wave (CW) jammers/interference. It is independent of the (CW only) jamming indicatordescribed in Jamming/interference indicator above.This monitor reports whether jamming has been detected or suspected by the receiver. The receivermonitors the background noise and looks for significant changes. Normally, with no interferencedetected, it will report "OK". If the receiver detects that the noise has risen above a preset threshold,the  receiver  reports  "Warning".  If  in  addition,  there  is  no  current  valid  fix,  the  receiver  reports"Critical".
> Enable jamming and interference monitor 

- src/ubx.cpp
From https://github.com/PX4/PX4-GPSDrivers/pull/57#issuecomment-776750937
> u-blox: increase update rate for M9N to 8Hz (from 5Hz)

- src/rtcm.h
Fairly simple function to pull the RTCM message id out of the buffer. 
Useful for message filtering.
> Adding messageId function to return what RTCM message is in the buffer.

- src/sbf.cpp
H @MatejFranceskin, thanks for implementing this driver, that help a lot.  
I am recently testing the septentrio's mosaic-X5, so I found this bug.
This bug will make fix_type always be 0 in the eastern hemisphere.
> sbf: fix longitude judgement bug

- src/ubx.cpp
This PR removes the UBX_CFG_KEY_CFG_I2COUTPROT_RTCM3X message to fix U-blox M9N failing to start. Tested on a Pixhawk 4 with a M8N and M9N GPS. Also tested on an ARK CAN GPS with a M9N.
> Remove UBX_CFG_KEY_CFG_I2COUTPROT_RTCM3X to fix M9N functionality

- src/nmea.cpp
- src/nmea.h
RTCM output in general receiver could be configured manually by user, so let support RTCM messages parsing just with warning.
> nmea: add rtcm parsing and add debug ouput

- src/femtomes.cpp
1. Change UNLOGALL command to UNLOGALL THISPORT for only clear current connected port of the device.
> Femto gps driver : Change "UNLOGALL" command

- src/ubx.cpp
- src/ubx.h
This PR adds moving baseline functionality on the ARK RTK GPS using the U-Blox F9P.
> UAVCAN/UART1 Moving Baseline for U-Blox F9P

- src/ubx.cpp
In the case where we subscribe to the UBX_MSG_NAV_VELNED message, the value we assign to vel_m_s is not the same as in the default case (UBX_MSG_NAV_PVT). Also according to the description of vel_m_s the value should correspond to the groundspeed (2d) and not the total 3d speed.
> always using groundspeed for vel_m_s in ubx driver

- src/ubx.cpp
I've been testing the dual GPS heading using the ublox F9P chip. I get big angles spikes (yellow vertical lines in the attached file) as the gps fix_type changes from float RTK to fixed RTK. Furthermore, I see no changes in the heading accuracy. 
Finally, as expected, I've observed that the heading estimates are always more precise in RTK fixed: 
A simple solution, for now, is to disable the GPS heading when we are in RTK float fix type. 
Note: I believe that @dagar and @bresch have also experienced drops in accuracy when switching from RTK float to RTK fixed fix type.
> Disable gps heading for UBX driver in RTK float fix type

- src/sbf.cpp
Before checking the CRC across header and payload, we need to check if the length is valid. If the length is longer than what we have read into the buffer, it must be invalid and we don't have to bother with the CRC.
This should fix a potential segfault where the CRC overruns the allocated buffer due to a corrupt length field.
Fixes #103 as discovered by @devbharat.
> sbf: fix overrun on invalid length

- src/ubx.cpp
- src/ubx.h
When using the U-blox ZED-F9P GPS module, users may want to use the GPS module's UART2 port to send or receive RTCM corrections using a Telemetry Radio, rather than hard wiring this port to another module. These radios operate at 57600 baud out of the box. But the UART2 baudrate is hard coded to 230400 baud. This PR allows us to configure the Baud Rate of the ZED-F9P's UART2 port through a QGC param.
Additionally, the existing modes that the **GPS_UBX_MODE** param covers misses one potential mode -- when a user is sending RTCM corrections from a _static_ base, or other _static_ correction source, directly to UART2. The existing modes that enable UART2 assume a moving base configuration. I've called this new mode **Rover With Static Base on UART2**. This mode is functionally equivalent to …
> ZED-F9P UART2 Baudrate Configurability and New UBX Mode.

- src/ubx.h
This fixes the UBXMode enum list to correspond to the param definition.
https://github.com/PX4/PX4-Autopilot/blob/main/src/drivers/gps/params.c#L105
> Move RoverWithStaticBaseUart2 to end of enum list

- src/ashtech.cpp
Fix Trimble/Ashtech position accuracy degrade caused by https://github.com/PX4/PX4-GPSDrivers/commit/038a13f7c2f3e2d28ac8cb6c018911902abe1a49
Issue:
https://github.com/PX4/PX4-GPSDrivers/issues/117#issue-1457227958
> Fix position accuracy loss caused by misplaced integer cast

- src/gps_helper.h
- src/ubx.cpp
- src/ubx.h
Support for U-Blox driver to be able to change protocols at the I2C interface.
Another part will be done at PX4 with param.
> ubx: add support for enabling/disabling protocols at the I2C interface

- src/ubx.cpp
As it can happen during normal module probing.
@cmic0
> ubx: turn CFG-GNSS message failure into UBX_DEBUG

- src/nmea.cpp
> NMEA: add baudrate 230400

- src/unicore.cpp
Clang-tidy complained, rightfully.
> unicore: use nullptr instead of NULL

- src/ubx.cpp
This PR allows for a moving base to receive RTCM corrections while outputting them as well.
QGC with Fixed Base -> Radio -> FC -> dronecan RTCMStream -> Moving Base -> dronecan  MovingBaselineData -> Rover with Heading
https://review.px4.io/plot_app?log=08626ac1-09c9-4ac5-a272-77a1fc0e61ca
> Enable RTCM input on moving base

- src/ubx.cpp
- src/ubx.h
This PR adds support for the UBX-RXM-RTCM message which gives feedback on whether the ublox module is using the RTCM data that is being sent to it.
```
nsh> gps status
INFO  [gps] Main GPS
INFO  [gps] protocol: UBX
INFO  [gps] status: OK, port: /dev/ttyS0, baudrate: 921600
INFO  [gps] sat info: disabled
INFO  [gps] rate reading:                  925 B/s
INFO  [gps] rate position:                1.00 Hz
INFO  [gps] rate velocity:                1.00 Hz
INFO  [gps] rate publication:             1.00 Hz
INFO  [gps] rate RTCM injection:         40.02 Hz
sensor_gps
timestamp: 244102098 (0.781204 seconds ago)
timestamp_sample: 0
time_utc_usec: 1684174039124558
device_id: 11141125 (Type: 0xAA, SERIAL:0 (0x00))
lat: 406203100
lon: -1118287492
alt: 1433548
alt_ellipsoid: 1414764
s_variance_m_s: …
```
> Add UBX_MSG_RXM_RTCM to monitor RTCM stats

- src/ubx.cpp
- src/ubx.h
It turns out that the MON-HW message is sent with a shorter length with protocol version 34 (e.g. uBlox M10).
For reference, see the interface description:
https://content.u-blox.com/sites/default/files/u-blox%20M10-SPG-5.00_InterfaceDescription_UBX-20053845.pdf at page 104 of 184.
This means we don't need to print a warning about a wrong length, and can just ignore the packet.
The data that we are interested in is also sent in the MON-RF message and already parsed in the driver.
> ubx: ignore deprecated MON-HW message

- src/ubx.cpp
Some recent updates to UBX support broke M10. M10 has no RTCM so any attempts to set RTCM related configuration values will cause a configuration failure.
> Fixing UBlox M10 support

- src/ubx.cpp
The current GPS driver in the autopilot system contains an issue when attempting to initialize communication with the NEO-M9N UBLOX module, which is integrated within the [TFGPS01](https://github.com/ThunderFly-aerospace/TFGPS01/). During communication, the GPS driver receives NACK (negative acknowledgment) when trying to configure the following messages:
1. `UBX_CFG_KEY_MSGOUT_UBX_NAV_HPPOSLLH_I2C`
2. `UBX_CFG_KEY_MSGOUT_UBX_NAV_RELPOSNED_I2C`
After a reading of the [NEO-M9N documentation](https://content.u-blox.com/sites/default/files/u-blox-M9-SPG-4.04_InterfaceDescription_UBX-21022436.pdf), i have discovered that these specific message types are not supported by the NEO-M9N receiver. Consequently, the GPS driver fails to establish proper communication with the module, leading to the …
> Fix unsupported message with NEO-M9N Ublox module.

- gps-parser-test.cpp
- src/nmea.cpp
- src/nmea.h
- src/unicore.cpp
- src/unicore.h
This add support to parse (but not use) the Unicore AGRICA message. This allows to determine whether we are talking to a UM982 and hence request the heading (UNIHEADINGA) message that we actually require.
FYI @vincentpoont2
> unicore: parse AGRICA message, request heading

- src/ashtech.cpp
- src/mtk.cpp
- src/nmea.cpp
- src/ubx.cpp
I had compilation errors when compiling with NO_MKTIME defined, for a number of reasons:
- `struct tm` not defined
- various variables set but not used, e.g. `ashtech_sec` in ashtech.cpp
by moving the NO_MKTIME conditional compilation flag, I removed these compilation errors, and also I believe skip unnecessary packet decoding, when the results of the decoding was not being used without `mktime`
I don't have the ability to test these changes on a PX4 target that has NO_MKTIME defined.
> move NO_MKTIME compilation flags

- src/ubx.cpp
Fixed the wrong mapping described in  Issue https://github.com/PX4/PX4-GPSDrivers/issues/145.
> ubx: fixed wrong mapping of UBX-NAV-SAT used parameter

- src/ubx.cpp
The valset for the jamming monitor fails for the NEO-F9P (Here 4 base), unless it's done as a separate valset like in this patch.
Currently, on top of #148.
> ubx: separate config for jamming monitor

- src/sbf.cpp
- src/ubx.cpp
Let's not assume that the user of the GPS library has this define for half pi, and just calculate it.
> sbf: simplify odd define

- src/gps_helper.h
- src/sbf.cpp
- src/ubx.cpp
- src/ubx.h
This PR adds support for the Ublox ZED-F9P-15B.
It appears that moving base is not currently working. I think because it was NAKing `UBX_CFG_KEY_MSGOUT_RTCM_3X_TYPE4072_0_UART1` and I had to turn it off. 
It looks like it doesn't support moving base. I will need to update the driver to only allow moving base for the normal F9P.
https://content.u-blox.com/sites/default/files/ZED-F9P_ProductSummary_UBX-17005151.pdf
> Ublox ZED-F9P-15B

- src/sbf.cpp
- src/sbf.h
The automatic base configuration would sometimes print weird port names as well as reconnect every few seconds to the receiver.
> sbf: fix issue with automatic base config in QGC

- src/ubx.h
Duplicated private access specifier removed
> ubx.h: Removed double access specifier

- src/nmea.cpp
The NMEA format allows for multiple fix quality characters. The default implementation allows only 4 of these items to be parsed from the stream. When using a newer UM980 GPS unit, it supports 5 different types and causes the parser to mis-read the altitude message. This results in the GPS altitude jumping to 0 whenever a GNS message is received. This resolves the issue by ignoring any additional characters in the parsed message.
The PR also adds the ability to intrepret GLL messages from the GPS.
Fixes #23903
- fixes a bug in the NMEA parsing that is specific to newer GPS units
For release notes:
```
Feature/Bugfix Add parsing for the GLL message and fix a parsing bug in the GNS if posMode is more than 4 chars
> bugfix: altitude parsing problem

- src/ubx.cpp
Digging into the F9P variant output rates, I found that they are slightly different. And the new L1L2 firmware lowers the output rate further.
We could go further and change the output rate based on RTCM being injected or not but that might get too complicated.
F9P L1L2 in firmware <1.50 the max update rate with 4 constellations is 9Hz without RTK and 7Hz with RTK
F9P L1L2 in firmware >=1.50 the max update rate with 4 constellations is 7Hz without RTK and 5Hz with RTK
F9P L1L5 the max update rate with 4 constellations is 8Hz without RTK and 7Hz with RTK
> Ublox update F9P output rates

- src/ubx.cpp
- src/ubx.h
While using a F9P with RTK, the parser suddenly got stuck in the RTCM parsing, due to `_decode_state` having an invalid state (out of the enum range). This causes a GPS driver restart, which causes a delay in receiving GPS data.
This was due to an overflow of the variable: `_buf` which is stored before `_decode_state` in memory:
```
ubx_buf_t               _buf{};
ubx_decode_state_t      _decode_state{};
```
Debugging showed, that an invalid length was parsed which is only partly checked in case of `UBX_MSG_RXM_RTCM`.
As that message has a fixed length, the easiest option is to directly check against the expected length.
> ubx: fix overflow

- src/ashtech.cpp
- src/ashtech.h
- src/femtomes.cpp
- src/femtomes.h
- src/nmea.cpp
- src/nmea.h
- src/rtcm.cpp
- src/rtcm.h
- src/sbf.cpp
- src/sbf.h
- src/ubx.cpp
- src/ubx.h
This is the first follow up to: https://github.com/PX4/PX4-Autopilot/pull/24491. The NAV + RTCM3 parser can block each other as both parsers are integrated into the same state machine. This can cause significant delay until the parser gets in sync again.
As can be seen in the attached screenshots, the remaining timeout is in general higher now and the deepest drop is not as low as before. This was the worst case scenario of many tests.
- Forward input data to both NAV + RTCM3 parser and keep their states separate, so they can not block each other
- Use CRC24 to verify if RTCM3 data is valid before forwarding it to the callback
- When either NAV or RTCM3 parsing is successful, reset both parsers to start sync again
I would like to keep the increased timeout until all remaining drops are …
> Improve RTCM3 parsing performance

- src/sbf.cpp
- src/sbf.h
This PR contains improvement regarding :
- Add base station information using PVTGeodetic messages.
- Re-order sbf message definition in a more cleaver way.
- Return special ret code when receiving message for base station infos to avoid timeout for the receiver.
These changes are part of another PR on QGC to add a base station configuration menu.
> Improve base station configuration

- src/ubx.h
We had a problem with ublox F9P GPSes where, after rebooting the flight controller, the receiver would either:
- Go completely offline
- Get stuck in an initialization loop
- Take a long time to start up
If it went completely offline, we would have to power-cycle the F9P board to get it back online. Interestingly, on a rover/moving base setup, only the moving base was affected.
We were unable to reproduce it on a test-bench setup, only on our drones. After a lot of debugging, we found that this is connected to RTCM injection. While the flight controller restarted, our companion computer still sends RTCM messages. Injecting these messages during receiver configuration appears to sometimes cause undefined behaviour during config. 
I haven't found the exact mechanism of how it fails (each …
> ubx: don't inject RTCM while configuring device
