PX4/PX4-GPSDrivers

- src/ubx.cpp
- src/ubx.h
> Some updates for UBX driver

- src/ashtech.cpp
Thanks @djmira92 for reporting
> ashtech: update the velocity rate for status output

- src/ashtech.cpp
- src/ashtech.h
> ashtech: make sure only GGA or PASHR,POS are used, ignore GGA if both received

- src/ubx.cpp
Signed-off-by: Roman <bapstroman@gmail.com>
> gps devices: added more baud rates to support bebop2

- src/ubx.cpp
Signed-off-by: Roman <bapstroman@gmail.com>
> removed unnecessary baud rate from gps driver

- src/ashtech.cpp
- src/mtk.cpp
- src/ubx.cpp
https://scan.coverity.com/projects/px4-firmware?tab=overview
> coverity initialization fixes

- src/ashtech.cpp
> ashtech simplify boolean expr

- src/ubx.cpp
- src/ubx.h
https://github.com/PX4/Firmware/pull/7470
> ublox allow setting dynModel

- src/gps_helper.h
- src/mtk.cpp
- src/ubx.cpp
There might be more to come here.
> Steps for time isolation on PX4

- src/sbf.cpp
- src/sbf.h
Support for Septentrio Binary Format (SBF)
> PR Support for Septentrio GPS

- src/sbf.cpp
- src/sbf.h
See individual commit messages for details.
@MatejFranceskin fyi
> Septentrio: fixes for Base Station

- src/emlid_reach.cpp
- src/emlid_reach.h
gps: Support for Emlid Reach
Support Emlid Reach in NMEA and ERB format,
including autodetect
Reported-by: Bastien Auneau <bastien.auneau@while-true.fr>
> gps: Support for Emlid Reach

- src/sbf.cpp
- src/sbf.h
Fixes #42 
@MatejFranceskin LMK what you think.
> SBF Updates

- src/sbf.cpp
Only found that now after doing some fast climbs and looking at estimator innovations.. :)
> sbf: report vertical velocity DOWN (converted from UP)

- src/ubx.cpp
RTK configuration is not supported, thus:
- only configure RTCM output for the base station
- make UBX_CFG_KEY_NAVHPG_DGNSSMODE optional
Fixes https://github.com/PX4/GpsDrivers/issues/50
Tested on F9P + M9N
> ubx: support NEO-M9N

- src/ashtech.cpp
- src/sbf.h
This will generate warnings to block the building process of QGC. See [related bug in QGC](https://github.com/mavlink/qgroundcontrol/pull/9143)
> replace non-ascii characters in source code

- src/femtomes.h
- src/gps_helper.h
- src/nmea.cpp
- src/nmea.h
From https://github.com/PX4/PX4-GPSDrivers/pull/74 with some cleanup & fixes.
Tested with a u-blox m8n set to NMEA output.
> Generic NMEA driver

- src/ubx.cpp
Removes the extra UART1 baudrate set per @bkueng 's review.
> Remove extra UART1 baudrate set

- src/ubx.cpp
The receive implementation in the UBX driver was waiting until no data was read for a timeout period before checking if it is ready to return. However, when the bus utilization is high, there might be no gap in the received data stream and as a result, the receive timeout is triggered. The driver is then reinitialized and potentially doesn't start again since the GPS device is still sending data at high rates and the configure logic times out due to the same check. The timeout (https://github.com/PX4/PX4-GPSDrivers/blob/main/src/ubx.h#L58) was recently increased (#91) which makes it more likely that this scenario happens.
With this PR the receive function returns immediately when both posllh and velned are received and doesn't wait until there is no data read.
> Return from GPSDriverUBX::receive when ready, don't wait until no data is received

- src/sbf.cpp
Fixed some unused variable fatal errors and some incorrect pi constants so that the code compiles for Qurt platform.
> Fixed compile errors for Qurt platform

- gps-parser-test.cpp
- src/nmea.cpp
- src/nmea.h
- src/unicore.cpp
- src/unicore.h
Backport of #140.
@dagar objections against a `release/1.14` branch for backports?
> [BACKPORT v1.14] unicore: parse AGRICA message, request heading

- src/sbf.cpp
Only astyle fix from https://github.com/PX4/PX4-GPSDrivers/pull/150
> SBF astyle fix 

- src/sbf.cpp
It needed a bit of trial and error to figure out why subsequent configurations in QGC would fail. I eventually settled on the current changes which basically:
- always set up input mode
- always disable all SBF messages to then enable them again
- remove all manual decoder inits and flushes
> sbf: fix subsequent init in QGC

- src/gps_helper.h
@julianoes what about something simple like this? That way nothing changes for most people and those that want can define a new include
> Allow Custom Definitions Inclusion

- .github/workflows/linux_debug.yml
- CMakeLists.txt
@julianoes this will prevent the problem of making a mistake like I did
> CI: Add gps-parser-test runner

- src/ashtech.h
- src/emlid_reach.h
- src/femtomes.h
- src/mtk.h
- src/nmea.h
- src/sbf.h
- src/ubx.h
@julianoes I'm an idiot and forgot to adjust the other files
> Fix Header Includes

- src/gps_helper.h
- src/ubx.cpp
- src/ubx.h
See https://github.com/PX4/PX4-Autopilot/pull/25241
> ubx: add option to wipe flash
